In [1]:
import torch

In [2]:
torch.__version__

'2.6.0.dev20241006'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [10]:
tensor2 = torch.tensor([2, 3, 4, 5])
print(tensor2)
print(tensor2.ndim)
#scalar2.item()

tensor([2, 3, 4, 5])
1


In [11]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
print(scalar.shape)
print(vector.shape)

torch.Size([])
torch.Size([2])


In [15]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX                    

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR =  torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR2 =  torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]], 
                        [[7, 8, 9],
                         [4, 5, 6],
                         [1, 2, 3]], 
                        [[9, 8, 7],
                         [6, 5, 4],
                         [3, 2, 1]]
                        ])
TENSOR2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]],

        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]])

In [24]:
TENSOR2.ndim

3

In [25]:
TENSOR2.shape

torch.Size([3, 3, 3])

In [ ]:
TENSOR3 =  torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]], 
                        [[7, 8, 9],
                         [1, 2, 3]], 
                        [[9, 8, 7]],
                        ])
print(TENSOR3)
print(TENSOR3.ndim)
print(TENSOR3.shape)