In [1]:
import torch

In [2]:
torch.__version__

'2.6.0.dev20241006'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [10]:
tensor2 = torch.tensor([2, 3, 4, 5])
print(tensor2)
print(tensor2.ndim)
#scalar2.item()

tensor([2, 3, 4, 5])
1


In [11]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
print(scalar.shape)
print(vector.shape)

torch.Size([])
torch.Size([2])


In [15]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX                    

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
TENSOR =  torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR2 =  torch.tensor([[[1, 2, 3],
                         [3, 6, 9],
                         [2, 4, 5]], 
                        [[7, 8, 9],
                         [4, 5, 6],
                         [1, 2, 3]], 
                        [[9, 8, 7],
                         [6, 5, 4],
                         [3, 2, 1]]
                        ])
TENSOR2

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]],

        [[9, 8, 7],
         [6, 5, 4],
         [3, 2, 1]]])

In [24]:
TENSOR2.ndim

3

In [25]:
TENSOR2.shape

torch.Size([3, 3, 3])

In [29]:
TENSOR3 =  torch.tensor([[[1, 2, 3],
                         [2, 4, 5]], 
                        [[7, 8, 9],
                         [1, 2, 3]], 
                        [[9, 8, 7],
                         [2, 4, 5]], 
                        ])
print(TENSOR3)
print(TENSOR3.ndim)
print(TENSOR3.shape)

tensor([[[1, 2, 3],
         [2, 4, 5]],

        [[7, 8, 9],
         [1, 2, 3]],

        [[9, 8, 7],
         [2, 4, 5]]])
3
torch.Size([3, 2, 3])


In [30]:
TENSOR4 = torch.tensor([[1, 3, 2],
                        [2, 6, 4],
                        [3, 9, 5]])
print(TENSOR4)
print(TENSOR4.ndim)
print(TENSOR4.shape)

tensor([[1, 3, 2],
        [2, 6, 4],
        [3, 9, 5]])
2
torch.Size([3, 3])


In [31]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.9655, 0.3348, 0.7679, 0.4683],
         [0.5455, 0.7085, 0.3454, 0.0384],
         [0.9374, 0.7838, 0.0555, 0.3816]]),
 torch.float32)

In [32]:
zeros = torch.zeros(3, 4)
zeros, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([3, 4]))

In [33]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [34]:
zero_to_ten = torch.arange(start=0, end=11, step=1)
print(zero_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [35]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9849, 0.2390, 0.4147, 0.8884],
        [0.0149, 0.7211, 0.7425, 0.5338],
        [0.4342, 0.8407, 0.2522, 0.4340]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [37]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor * 10

tensor([10, 20, 30])

In [39]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [40]:
tensor = torch.tensor([1, 2, 3])
tensor * tensor

tensor([1, 4, 9])

In [41]:
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
tensor @ tensor

tensor(14)

In [43]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 821 µs, sys: 1.44 ms, total: 2.27 ms
Wall time: 2.39 ms


tensor(14)

In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 33 µs, sys: 9 µs, total: 42 µs
Wall time: 42.9 µs


tensor(14)

In [45]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [48]:
tensor_A.matmul(tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [51]:
torch.matmul(tensor_A, tensor_B.T)


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [52]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [50]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [53]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [57]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)
print(f"Input Shape: {x.shape}")
print(f"Output: {output}")
print(f"Output Shape: {output.shape}")

Input Shape: torch.Size([3, 2])
Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Output Shape: torch.Size([3, 6])


In [58]:
linear.weight, linear.bias

(Parameter containing:
 tensor([[ 0.5406,  0.5869],
         [-0.1657,  0.6496],
         [-0.1549,  0.1427],
         [-0.3443,  0.4153],
         [ 0.6233, -0.5188],
         [ 0.6146,  0.1323]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
        requires_grad=True))

In [60]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [62]:
print(f"Mean: {x.mean()}") # this will error

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [63]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [64]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [65]:
x_reshaped = x.reshape(1, 7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [66]:
x_reshaped.shape

torch.Size([1, 7])

In [67]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [68]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [69]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [70]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [71]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [75]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [76]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [77]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [78]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 100, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 100, 3])
New shape: torch.Size([3, 224, 100])


In [79]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [80]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [81]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7899, 0.6391, 0.7447, 0.5518],
        [0.0720, 0.1913, 0.2736, 0.8441],
        [0.6300, 0.0786, 0.5852, 0.6787]])

Tensor B:
tensor([[0.6495, 0.1106, 0.3819, 0.7920],
        [0.9512, 0.5110, 0.6190, 0.2634],
        [0.3695, 0.6231, 0.7981, 0.8978]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [85]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [86]:
import torch
torch.cuda.is_available()

False

In [87]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


In [88]:
torch.cuda.device_count()

0

In [89]:
# Check for Apple Silicon GPU
import torch
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [90]:
# Set device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [91]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'mps'

In [92]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [94]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

In [95]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [99]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])